### ISSUE TITLE
投票（poll）で投票が無くても投票を作れる

### ISSUE THREAD

**Issue by narikakun** [Yui-Discord-Project/Yui-Discord-Project#3]
投票（poll）で投票が無くても投票を作れる問題

## 本来の動作
選択肢が１つ以上なければ必要なパラメーターが不足しているとエラーを出すようにする。

## スクリーンショット
![image](https://user-images.githubusercontent.com/35885585/130061909-9ee9f4ce-806e-428f-adca-53af2dfd6bc7.png)

**Comment by Kigou-No1** [comment]
修正しました。
